//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWebApi.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại hoặc chưa xác thực..
        /// </summary>
        public static string ACCOUNT_FAIL {
            get {
                return ResourceManager.GetString("ACCOUNT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực thất bại..
        /// </summary>
        public static string COMFIRMED_FAIL {
            get {
                return ResourceManager.GetString("COMFIRMED_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực thành công..
        /// </summary>
        public static string COMFIRMED_SUCCESS {
            get {
                return ResourceManager.GetString("COMFIRMED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khởi tạo thất bại..
        /// </summary>
        public static string CREATE_FAIL {
            get {
                return ResourceManager.GetString("CREATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khởi tạo thành công..
        /// </summary>
        public static string CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc phải có dữ diệu.
        /// </summary>
        public static string DATA_IS_REQUIRED {
            get {
                return ResourceManager.GetString("DATA_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại..
        /// </summary>
        public static string DELETE_FAIL {
            get {
                return ResourceManager.GetString("DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công..
        /// </summary>
        public static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra mật khẩu.
        /// </summary>
        public static string FORGOT_PASSWORD_BODY {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu lấy lại mật khẩu không thành công.
        /// </summary>
        public static string FORGOT_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào mail để lấy link đổi mật khẩu..
        /// </summary>
        public static string FORGOT_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thất bại..
        /// </summary>
        public static string GET_FAIL {
            get {
                return ResourceManager.GetString("GET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công..
        /// </summary>
        public static string GET_SUCCESS {
            get {
                return ResourceManager.GetString("GET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác..
        /// </summary>
        public static string LOGIN_FAIL {
            get {
                return ResourceManager.GetString("LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công..
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thất bại..
        /// </summary>
        public static string LOGOUT_FAIL {
            get {
                return ResourceManager.GetString("LOGOUT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công..
        /// </summary>
        public static string LOGOUT_SUCCESS {
            get {
                return ResourceManager.GetString("LOGOUT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ kí tự.
        /// </summary>
        public static string MIN_LENGTH {
            get {
                return ResourceManager.GetString("MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại..
        /// </summary>
        public static string NOT_ACCOUNT {
            get {
                return ResourceManager.GetString("NOT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại..
        /// </summary>
        public static string NOT_DATA {
            get {
                return ResourceManager.GetString("NOT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có mã toke..
        /// </summary>
        public static string NOT_TOKEN {
            get {
                return ResourceManager.GetString("NOT_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp nhau.
        /// </summary>
        public static string PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại..
        /// </summary>
        public static string REGISTER_FAIL {
            get {
                return ResourceManager.GetString("REGISTER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công..
        /// </summary>
        public static string REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thất bại..
        /// </summary>
        public static string RESETPASSWORD_FAIL {
            get {
                return ResourceManager.GetString("RESETPASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công..
        /// </summary>
        public static string RESETPASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("RESETPASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận email.
        /// </summary>
        public static string SEND_MAIL_CONFIRMED {
            get {
                return ResourceManager.GetString("SEND_MAIL_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi nội dung email.
        /// </summary>
        public static string SEND_MAIL_CONFIRMED_BODY {
            get {
                return ResourceManager.GetString("SEND_MAIL_CONFIRMED_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thất bại..
        /// </summary>
        public static string UPDATE_FAIL {
            get {
                return ResourceManager.GetString("UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thành công..
        /// </summary>
        public static string UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải giống nhau..
        /// </summary>
        public static string VALIDATION_COMPARE {
            get {
                return ResourceManager.GetString("VALIDATION_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng.
        /// </summary>
        public static string VALIDATION_DISPLAY {
            get {
                return ResourceManager.GetString("VALIDATION_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} ký tự..
        /// </summary>
        public static string VALIDATION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được it hơn {1} ký tự..
        /// </summary>
        public static string VALIDATION_MIN_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống..
        /// </summary>
        public static string VALIDATION_NOT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu xác thực.
        /// </summary>
        public static string VERIFICATION_REQUIRED {
            get {
                return ResourceManager.GetString("VERIFICATION_REQUIRED", resourceCulture);
            }
        }
    }
}
