// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Data;

namespace MyWebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220418104525_SeeDatabase")]
    partial class SeeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebApi.Data.CataLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CataLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Detergents"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tv"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mobie Phone"
                        });
                });

            modelBuilder.Entity("MyWebApi.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CataLogId")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CataLogId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CataLogId = 1,
                            Context = "Dung dịch tẩy rửa bồn cầu ",
                            Discount = (byte)0,
                            Name = "Vim",
                            Price = 45000.0
                        },
                        new
                        {
                            Id = 2,
                            CataLogId = 2,
                            Context = " Tx xem siêu nét từ Vinmart",
                            Discount = (byte)10,
                            Name = "Tv Vinmart",
                            Price = 500000.0
                        },
                        new
                        {
                            Id = 3,
                            CataLogId = 3,
                            Context = "Điện Thoại Sam Sung mới nhất",
                            Discount = (byte)5,
                            Name = "SamSung Galaxy S10",
                            Price = 1200000.0
                        },
                        new
                        {
                            Id = 4,
                            CataLogId = 3,
                            Context = "Điện Thoại Apple mới nhất",
                            Discount = (byte)10,
                            Name = "Iphone 11",
                            Price = 1500000.0
                        });
                });

            modelBuilder.Entity("MyWebApi.Data.Product", b =>
                {
                    b.HasOne("MyWebApi.Data.CataLog", "CataLog")
                        .WithMany()
                        .HasForeignKey("CataLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CataLog");
                });
#pragma warning restore 612, 618
        }
    }
}
